a=input()
##print(a.upper())
##print(a.lower())
##print(a.capitalize())
##print(a.split('_'))
##print(a.find("a"))
##print(a.index("a"))
##print(a.rfind('a'))
##print(a.rindex('a'))
##print(a.center(20))
##print(a.strip())
##print(a.startswith('s'))
##print(a.endswith("a"))
##print(a.replace("a","e"))
print(a[ : : -1])
print(a[0:5])
print(a[4:0:-1])

